// Action group legend constants generated from updated AG mapping.
// These globals allow the rest of the program suite to refer to
// descriptive names instead of hard-coded AG numbers.

DECLARE GLOBAL AG_LEGS TO 1.
DECLARE GLOBAL AG_FAN_SYSTEM TO 2.
DECLARE GLOBAL AG_JETS TO 3.
DECLARE GLOBAL AG_REVERSE_FAN TO 4.
DECLARE GLOBAL AG_FLAPS_DOWN TO 5.
DECLARE GLOBAL AG_FLAPS_UP TO 6.

DECLARE GLOBAL AG_LIGHTS_RUNWAY TO 51.
DECLARE GLOBAL AG_LIGHTS_GONDO TO 52.
DECLARE GLOBAL AG_LIGHTS_HAB TO 53.
DECLARE GLOBAL AG_LIGHTS_ACCENT TO 54.
DECLARE GLOBAL AG_LIGHTS_SPOT TO 55.
DECLARE GLOBAL AG_LIGHTS_FLOOD TO 56.
DECLARE GLOBAL AG_LIGHTS_GROUND_EFFECT TO 57.

DECLARE GLOBAL AG_MAIN_HANGAR_DOOR TO 36.
DECLARE GLOBAL AG_COOLING_SYSTEM TO 50.
DECLARE GLOBAL AG_SIDE_SOLAR_OPEN TO 58.
DECLARE GLOBAL AG_BOOM_DEPLOY TO 59.
DECLARE GLOBAL AG_BOOM_SOLAR_DEPLOY TO 60.
DECLARE GLOBAL AG_DRILL_MOTORS TO 80.
DECLARE GLOBAL AG_DRILL_LOCKS TO 81.

DECLARE GLOBAL AG_LONG_COMMS_ON TO 22.
DECLARE GLOBAL AG_HGA_ON TO 23.
DECLARE GLOBAL AG_LONG_COMMS_RETRACT TO 47.
DECLARE GLOBAL AG_SHORT_COMMS_RETRACT TO 48.

DECLARE GLOBAL AG_ABORT_DO_NOT_PRESS TO 112.

// Upper marquee light rows (habitat gallery) and runway strip lights
DECLARE GLOBAL AG_MARQUEE_LOWER_ROW TO LIST(101, 102, 111, 136, 103, 104, 105, 106, 107, 108, 109).
DECLARE GLOBAL AG_MARQUEE_UPPER_ROW TO LIST(126, 127, 128, 129, 130, 131, 132, 133, 134).
